language: android
sudo: required
dist: trusty
group: deprecated-2017Q4
env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
    - addon-google_apis-google-22
    - addon-google_apis-google-25
    - extra
script:
   - chmod +x ./gradlew
   - ./gradlew build testRelease assembleRelease
   
